FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.producer.txt .
RUN pip install --no-cache-dir -r requirements.producer.txt

# Copy source
COPY binance_websocket.py .

CMD ["python", "binance_websocket.py"]