# =============================================================
# trino/catalog/postgresql.properties
# Connector: Trino → PostgreSQL (database aplikasi btcdb)
# Digunakan oleh Streamlit untuk query tabel operasional
# =============================================================

connector.name=postgresql

# Koneksi ke PostgreSQL container (nama service dalam bigdata_net)
connection-url=jdbc:postgresql://postgres:5432/btcdb
connection-user=kelompok4_ipbd
connection-password=k4ipbd_postgres_2026

# Izinkan push-down predicate untuk performa lebih baik
postgresql.include-system-tables=false

# Mapping tipe data
case-insensitive-name-matching=true