apiVersion: 1
contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: telegram-alert
        type: telegram
        settings:
          bottoken: "${TELEGRAM_BOT_TOKEN}"
          chatid: "${TELEGRAM_CHAT_ID}"
        disableResolveMessage: false
